### ISSUE TITLE
Fix once user/github user has been forgotten and they reregister it breaks everytinh

### ISSUE THREAD

**Issue by SforziniVictor** [ITU-BDSA2024-GROUP4/Chirp#184]
Fix once user/github user has been forgotten and they reregister it breaks everyting. Currently only fix is to remove db. select * from AspNetUsers in db you can still spot the deleted users, these will have to be removed also will look at it later

**Comment by BergurDavidsen** [comment]
Can't reproduce bug, so is probably fixed at somepoint. maybe #176
